# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

# paginate: 10 # pagination basted on number of posts
exclude: ['watch.sh', 'sass', 'style.scss'] # files to exclude

paginate: 10
premalink: pretty
markdown: redcarpet
highlighter: true
